name: ci cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint

      - name: docker compose
        run: docker compose -f docker-compose.test.yml up -d --wait

      - name: test
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
